### ISSUE TITLE
Where is the wrapper for the SCT pipeline?

### ISSUE THREAD

**Issue by jcohenadad** [inspiredstudy/inspiredsct#1]
@jstutters it was my understanding that the [sct-pipeline](https://github.com/sct-pipeline/inspired) is wrapped with Snakemake, however I cannot see where this wrapping code is ([this repos](https://github.com/inspiredstudy/inspiredsnakemake), with latest commit https://github.com/inspiredstudy/inspiredsnakemake/commit/0213a47f8d070ffc478153698c846693d0a9a725, only concerns the brain). I would notably like to see what version of the sct-pipeline is bundled with the wrapper.

**Comment by jstutters** [comment]
Repository had fallen behind my local work.  https://github.com/inspiredstudy/inspiredsnakemake/blob/master/template/default/Snakefile.j2 is now up-to-date.  The expected version of SCT is v4.0.0-beta.5.  I might also need to create a repo to reflect the move from docker to singularity.

**Comment by jcohenadad** [comment]
i don't see SCT's release info in https://github.com/inspiredstudy/inspiredsnakemake/blob/master/template/default/Snakefile.j2, which is a problem for traceability. Why not including SCT's install in your singularity config file?

**Comment by jcohenadad** [comment]
i guess there is [this docker config](https://github.com/inspiredstudy/inspireddocker/blob/master/Dockerfile), which is probably no more used as per [your comment](https://github.com/inspiredstudy/inspiredsct/issues/1#issuecomment-664510049) (points to a local sct_v3.1.1 install). 

i suggest to centralize the documentation about where to find the config files, for transparency and reproducibility
